### ISSUE TITLE
Add better filtering for kernel tracing.

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#151]
Need to improve this to support proper filtering, not sure what best approach is yet.

https://github.com/decaf-emu/decaf-emu/commit/e42f4015881ed8339d1b7203da941c5bd19acf9c

**Comment by brett19** [comment]
Since our kernel calls are registered with libcpu as a sequential list of KC_ID's.  I think that the best course of action might to be to push this logic down a level to the HLE invocation stage.  This means that we will be able to enable/disable specific KC invocations at the HLE layer, which means checking if a method should be invoked with tracing or not can will simply be a lookup rather than a string comparison.

**Comment by brett19** [comment]
On second glance at our current code, this is actually already fully implemented.  We just need to add the 'tracing' property to HleFunction's, and then provide a configuration method to actually control its value.  HleModules already maintain a list of their respective HleFunctions, and HleFunction already controls whether the ppcinvoker is triggered with logging or not.

**Comment by exjam** [comment]
Oh that's a great shout actually, doing it further up the call chain to avoid expensive comparisons would be great
