### ISSUE TITLE
Research texture dumping and un-tiling

### ISSUE THREAD

**Issue by zhuowei** [decaf-emu/decaf-emu#18]
All the Wii U textures I've seen are passed to GX2SetPixelTexture already swizzled; it would be nice to have a feature to unswizzle them and dump them to disk for inspection.

(If it's too early to consider texture related stuff, feel free to close this)

The tiling/untiling algorithm is implemented in a few libraries:

- [AddrLib](http://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/winsys/amdgpu/drm/addrlib?h=amdgpu) (in Mesa) - official AMD code; complex, only supports r800 (but close enough to r600 that it might work), complex API
- [Mesa's old R600 driver](https://chromium.googlesource.com/chromium/deps/mesa/+/6da96107e2467063c72e1ec5804f0618a6ce83d3/src/mesa/drivers/dri/r600/radeon_span.c) - simple, no out-of-the box support for untiling compressed textures
- [EveryFileExplorer's texture support](https://github.com/Gericom/EveryFileExplorer/tree/master/WiiU/GPU) - decompresses dxt5 textures before untiling; only supports one type of tiling; also has a copy of a decompiled R600 AddrLib

Should we look into these libraries to see whether we can integrate one of them to process textures?

**Comment by brett19** [comment]
If you want to try and get something like this working (loading of textures onto GPU, or to disk), I'm sure that would be immensely helpful.  I would honestly suggest the Mesa R600 driver or a cleaned up version of the EveryFileExplorer source (converted to C++ as well).

**Comment by exjam** [comment]
None of the games I have testing have got to the point of rendering so I have not actually done much research into the graphics side of things. I know there is a (binary only) tool out there called TexConv2 which will translate .GTX textures to .DDS.

That EveryFileExplorer seems pretty suitable due to being targeted to the WiiU, and from the code it clearly was all reversed from what I assume was TexConv2.

Although it is nice to have a texture -> bitmap dumper, for emulation I only really care about being able to unswizzle/untile to a format that OpenGL can render directly (e.g. gtx can unswizzle to DXT5 and there is no need for us to write a DXT5 decoder as you can pass it straight to hardware using the s3tc extension).

**Comment by zhuowei** [comment]
Since I couldn't get AddrLib to work, I tried making the Mesa code work for dxt5 textures by looking at how AddrLib does the microtile swizzling for dxt5 textures and by grabbing the parameters from EveryFileExplorer; the result is https://github.com/zhuowei/wiiu-tools/blob/master/untile/main.cpp.

It managed to unswizzle one 128x128 dxt5 texture from Amiibo Settings, but didn't work for the two dxt1 textures.

**Comment by brett19** [comment]
Hey @zhuowei,
Have you made any more progress with unswizzling/untiling?  We are starting to look at processing of textures for rendering.
Cheers, Brett

**Comment by ADormant** [comment]
@exjam Could this feature be used for texture replacement like in Dolphin?

**Comment by exjam** [comment]
Turns out it was very similar to the r600 but with added bank rotation, swizzle, swapping and channel rotation. It's now implemented :).

f4fe207bf9499cd4549d85868d130d7a1b72d848
