### ISSUE TITLE
Stencil buffer binding is incorrect.

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#330]
Currently, if the incoming buffer is not of the 3 stencil buffer formats, we set stencil_enable to off.  This causes an issue because some games set a format that has room for the stencil, and then expect to use it (there is no difference from the GPUs perspective).  It looks like we need to bind stencil_depth always maybe?  pcmaker dropped the if statement entirely and stuff started working again.

**Comment by brett19** [comment]
Hey @achurch, any idea if dropping that statement is reasonable?

**Comment by achurch** [comment]
Hmm, I'm a bit confused. We only disable the stencil buffer if it's a format that doesn't have a stencil component in the first place, so how does it "have room for the stencil"? (I assume you're talking about this line: https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/gpu/opengl/opengl_depthbuffer.cpp#L38)

I actually don't see how dropping that if statement would let rendering work in the first place, since if the depth buiffer doesn't have a stencil component, binding it to the stencil attachment point would cause an incomplete framebuffer.

Are there any stencil-renderable formats missing from the test, maybe?

**Comment by brett19** [comment]
I believe all of the formats that have "X" (indicating that they are ignored) are still stencil-renderable.  In spite of the format having those bits unused.

**Comment by achurch** [comment]
I only see one format with X (FMT_X24_8_32_FLOAT) -- are there others?

Actually, now that I look at the list I see that there are two bit orders for 24+8 (24_8 and 8_24) -- that might be what's missing.
