### ISSUE TITLE
Chompy Chomp Chomp Party - Graphical bugs (trace included)

### ISSUE THREAD

**Issue by JohnGodgames** [decaf-emu/decaf-emu#351]
@achurch ping

![chompy 1](https://cloud.githubusercontent.com/assets/11453507/17897380/4902c62a-6954-11e6-8627-0f56063600bd.PNG)
![chompy 3](https://cloud.githubusercontent.com/assets/11453507/17897378/48fc660e-6954-11e6-8fa3-4d8c66a6895f.PNG)
![chompy 2](https://cloud.githubusercontent.com/assets/11453507/17897379/48fd22d8-6954-11e6-814d-83eb2479c551.PNG)

[Reference video](https://www.youtube.com/watch?v=WkCJzvO6Lew)

**[LOG](http://pasted.co/f969016d)**

**[TRACE DOWNLOAD (apitrace)](https://mega.nz/#!PN8TEDxB!bByOCHf8DpIVF4oAkuq-k6nDSHLoUW7qjNZEIi9vJls)**

**Comment by achurch** [comment]
@pcmaker Sorry, I don't see anything obvious. If this is a regression, try bisecting to find the change responsible.

For future reference, it helps in debugging GL traces if you set `gpu::force_sync` to true in your config file -- that forces exactly one GL frame per emulated frame, instead of having GL calls for the same emulated frame spread out over multiple GL frames. Setting `gpu::debug` to true also helps by adding labels to GL objects and unbinding unused objects to reduce UI clutter in apitrace.

**Comment by JohnGodgames** [comment]
It's not a regression.These bugs still persist when game boots for firs time...btw I've set that configs.

**Comment by brett19** [comment]
Closing this as it predates the Vulkan backend which likely doesn't exhibit this issue.

**Comment by exjam** [comment]
There are still lots of graphical bugs in this game:
https://puu.sh/ERwab/9dbd80dd40.png
https://puu.sh/ERwaO/46fdc9a154.png
https://puu.sh/ERwbh/62c13f748d.png
