### ISSUE TITLE
a better guide for compiling

### ISSUE THREAD

**Issue by Gamedev1909** [decaf-emu/decaf-emu#395]
Could we have a better written guide for linux and windows please

**Comment by Krakn** [comment]
I'll whip something up.

**Comment by exjam** [comment]
May I bring attention to the README.md where it says:

> **Support**
> None, this is an in-development project and user support is not provided.
> **Binaries**
> The latest Windows AppVeyor build is available from:
> https://ci.appveyor.com/api/projects/exjam/decaf-emu/artifacts/decaf-bin.zip

This is a standard CMake project, hence why there is no thorough build instructions.

If you really want your hand held then maybe citra's screenshot guide can help... it even includes screenshots showing you how to download CMake!
https://github.com/citra-emu/citra/wiki/Building-For-Windows

**Comment by Gamedev1909** [comment]
Wow that was extremely childish i expected better from you guys but in the end i guess all emulator devs are the same

**Comment by PickledChris** [comment]
i miss the old decaf, keeps adding code decaf,
has loads of threads decaf, beats cemu dead decaf,
i hate the new decaf, no more commits decaf,
just shitposts issues decaf, devs are rude pricks decaf

**Comment by RHY3756547** [comment]
wow guys no need to be so rude all i wanted to ask was if you could make it easier to build complex in development software just like how easy it is to develop a vulkan renderer just switch the dropdown box in unreal engine to vulkan its that easy thats the power of vulkan since its amd mantle reborn and anything by amd is flawless perfect in my book if you are developing this emulator with nvidia you should be ashamed i mean really this is the reason zelda botw doesnt work a day after release exzap exjam you exes are the same

**Comment by ds84182** [comment]
Can someone lock this? I didn't sign up to the "incoherent babbling" mailing list.
