### ISSUE TITLE
Scores drawn as 0 or 10 in NES Remix

### ISSUE THREAD

**Issue by CarlKenner** [decaf-emu/decaf-emu#405]

**Comment by exjam** [comment]
This is because NES Remix does not explicitly flush the memory (DCFlushRange) where it stores these values (cant remember if it's in a uniform buffer or texture or vertex buffer or whatever) so we don't pick up the changes in the gpu.

This is a hard problem to solve because the only way around it is to monitor all GPU resources for changes, which could be incredibly slow for games which use hundreds of MB of graphics memory.

Related issue: https://github.com/decaf-emu/decaf-emu/issues/281
Related PR: https://github.com/decaf-emu/decaf-emu/pull/362

I mean it's worth leaving this open, but it's really a wont-fix right now.

**Comment by CarlKenner** [comment]
Is there a (host) operating system mechanism for monitoring when a block of memory is touched?

**Comment by exjam** [comment]
You can mark memory pages as read only and catch exceptions. I have no clue what the performance of such a mechanism is though.

Although that has the limitations of restrictions to page alignment, you could do something funky for non page aligned buffers like only mark read-only pages on the parts of a texture which fully span a page and hash the parts of the texture which are on either sides of a page boundary.

**Comment by CarlKenner** [comment]
BTW, the game works fine in Cemu, and doesn't have a specific Cemu profile.

**Comment by exjam** [comment]
Hmm maybe I was wrong then, it's been a long time since I saw that bug..

**Comment by exjam** [comment]
This is fixed in Vulkan backend.
