### ISSUE TITLE
GX2SetVertexUniformBlock gets called with absurd sizes

### ISSUE THREAD

**Issue by CarlKenner** [decaf-emu/decaf-emu#409]
It seems to still work, but there may be some performance issues here.

For example, in Xenoblade, it calls it with size 192000 for a U_Bone uniform block whose real size is only 96 (as far as I can tell). This is a size of 0x2EE00, but we mask it with 0x1FF00 before passing it to the pm4, so it becomes 0x0EE00 or 60928.

**Comment by exjam** [comment]
Well without investigating the issue I assume it's because the GPU on the Wii U just doesn't care how big the size is due to the unified memory model meaning there is no data upload, you just set a pointer and a max size to registers and the GPU will read from it as needed.

Where are you seeing this 0x1FF00 mask on size? We just set SQ_VTX_CONSTANT_WORD1_N.SIZE (which is 32 bits) to size - 1.
https://github.com/decaf-emu/decaf-emu/blob/20eb74bfacf7ddf3bd79583f471f88dbe76871c0/src/libdecaf/src/modules/gx2/gx2_shaders.cpp#L363-L375
https://github.com/decaf-emu/decaf-emu/blob/20eb74bfacf7ddf3bd79583f471f88dbe76871c0/src/libdecaf/src/gpu/latte_registers_sq.h#L106

**Comment by exjam** [comment]
Oh right nevermind, it's SQ_ALU_CONST_BUFFER_SIZE_VS_0  which is set to size256 = ((size + 255) >> 8) & 0x1FF;

**Comment by CarlKenner** [comment]
Why are we doing & 0x1FF anyway?

I think the Wii U has a 16-bit limit on uniform offsets (with flags in the upper 16 bits), which implies that the size is always going to be <= 0x10000. Although that might just be for the register mode and not for uniform blocks, I don't know.

**Comment by exjam** [comment]
It's copied from gx2.rpl, unless I misinterpreted the rlwimi operation here:
```
GX2SetVertexUniformBlock
mr      r27, r4
...
mr      r9, 0
addi    r8, r27, 0xff
rlwimi  r9, r8, 24, 23, 31
stw     r9, 0x48+var_34(r1)
...
stw     r9, 0(r12)
lwz     r7, 0x48+var_34(r1)
stw     r7, 0(r12)
```

**Comment by CarlKenner** [comment]
I get it now. The size has to be less than 0x20000, because uniform locations are 15 bits, and they are multiplied by 4.
