### ISSUE TITLE
DX12 Progress?

### ISSUE THREAD

**Issue by Gamedev1909** [decaf-emu/decaf-emu#429]
AMD users are waiting for opengl to be fixed or DX12 progress i was hoping brett was still working on it in some spare time ?

**Comment by VelocityRa** [comment]
I really doubt that he is, considering the last commit to the dx12 branch was last October and Brett has not been working on Decaf the past few months anyway.

A Vulkan backend is something that exjam has expressed interest in, though that's quite a bit of work and I'm not sure where it lies on his priorities right now.

What issues are you having exactly?
On #317 it seems like the issue was fixed for [this](https://github.com/decaf-emu/decaf-emu/issues/317#issuecomment-272007566) person, was it not for you? If so, please supply a log there.
IMHO right now that's your best best, as opposed to DX12 or Vulkan.

**Comment by Gamedev1909** [comment]
Mesa also doesnt work for amd on linux mint but i mean on windows opengl has been broken for years now pretty much

**Comment by FernandoS27** [comment]
For starters the ogl backend is not finished. I doubt any new backend will be started/worked on until decaf becomes stable enough.
