### ISSUE TITLE
Sonic Lost World - Unsupported texture dim: 6

### ISSUE THREAD

**Issue by slashiee** [decaf-emu/decaf-emu#440]
Upon booting the game, the emulator crashes with an unsupported texture dim error. I would not be surprised if this error was caused by the fact that I have an AMD GPU.

Radeon Software Version - 17.4.4
Windows Version - Windows 10 (64 bit)
CPU Type - AMD FX(tm)-6300 Six-Core Processor
Graphics Chipset - AMD Radeon (TM) R7 360 Series

Log File: [Sonic Lost World_2017-05-12_22-58.txt](https://github.com/decaf-emu/decaf-emu/files/998372/Sonic.Lost.World_2017-05-12_22-58.txt)

If this also affects NVIDIA GPUs, then it would more than likely be a regression because [History of decaf-emu in screenshots - Part 2](http://wecode.ninja/history-of-decaf-emu-in-screenshots-part-2/) showed Sonic Lost World getting to Windy Hill Zone 1, and that was back in August 29th, 2016.
![image](https://cloud.githubusercontent.com/assets/15317421/26022867/d55d9e72-3764-11e7-962c-52b5a66c6d88.png)

**Comment by VelocityRa** [comment]
That error appears 5 times in `opengl_surface.cpp` and in all cases I don't see anything which could cause issues with AMD _specifically_, so if I had to guess I'd say that is is indeed a regression.

I'll try to test on NVidia just to be sure (and to pinpoint where exactly it asserts).

**Comment by VelocityRa** [comment]
As expected, I'm getting the same error on Nvidia,
Happens [here](https://github.com/decaf-emu/decaf-emu/blob/master/src/libgpu/src/opengl/opengl_surface.cpp#L684) because a `SQ_TEX_DIM` of type `DIM_2D_MSAA` is requested.

I hacked it around by supplying the texture supplied to `DIM_2D` (without MSAA) and it gets to the main menu,

![image](https://cloud.githubusercontent.com/assets/6632271/26502322/20d5351e-4245-11e7-9a33-5d092fb23dc1.png)

and then in-game like the pic your provided.

![image](https://cloud.githubusercontent.com/assets/6632271/26502625/1f0da6b6-4246-11e7-81ed-50d04a462421.png)

![image](https://cloud.githubusercontent.com/assets/6632271/26502633/2c29429c-4246-11e7-8629-cc8573a2f808.png)

So, **I don't believe it was a regression**, but a conscious decision.

The reason it doesn't work now might be because OpenGL didn't support a fitting texture format to supply (the reason it worked before was innacurate emulation). This might be easier to fix in the future, with Vulkan.

**Comment by brett19** [comment]
OpenGL is no longer used, and texture dim 6 is supported (ish).
