### ISSUE TITLE
Add register allocator to JIT

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#92]
Just a basic LRU thingy will do, currently we just move to/from memory and use fixed registers.

**Comment by brett19** [comment]
I did this with the previous JIT code, and it improved performance considerably.  The main gotchya's here are that some x64 instructions require specific registers, before we perform any KC calls, we must flush our local register cache to the CoreRegs* structure, this is because any KC could access or modify this variables, and additionally might switch Core's entirely, invalidating any of the shared cache without it having been flushed.  In addition to this, any branches (into or outside of JIT) and any JIT fallback calls also must flush our local cache.  It's worth mentioning as well that we will need to be cautious about where we allow interrupts to occur as well, since these will also force us to flush the cache.

As an aside, in the future when we want to do cross-block optimizations, especially surrounding JIT allocation.
